name: build-and-release

on:
  push:
    branches:
      - main  # Trigger the workflow for commits pushed to the main branch
    tags:
      - 'v1.0.0'  # Run on version tags like v1.0.0 to create releases automatically

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]  # Specify the OS to build on (use windows to generate .exe)
    runs-on: ${{ matrix.os }}

    steps:
      # 1. Check out the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: pos-app

      # 4. Build and release using electron-builder
      - name: Build and Release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          NODE_ENV: production
